Remove defunct mod/assignment
remotelearner/moodle-block_grade_me pull request #88
Opened 2024-06-14 17:25 UTC by Syxton

mod/assignment was removed in Moodle 4.2.
also fixes: #86

2024-10-10 06:58 UTC, Junosprite007 requested changes
Glad to see someone tackled this. Looks fine except for your choice to remove the 'assign_submission' table in the test file: tests/fixtures/block_grade_me.xml

Could you please explain your reasoning for removing this table? It seems that this table is a part of the not-out-of-date 'assign' naming convention, thus it should be kept, no? I haven't looked a ton into this, but could you explain your reasoning a bit, or make a change to keep that particular table?

2024-10-14 12:52 UTC, Syxton commented
@Junosprite007 sorry I've been out of town.  You are correct, I took out more of the xml than I should have there.  Added back.

2024-10-29 01:18 UTC, logan-reynolds commented
Thank you for contributions here and my apologies if a merge-able PR was missed, as I had already started similar fixes for removal of old "Assignment" across all versions before I realized there was additional dialogue and commits on this issue.  Please feel free to check against the new versions v4.3.0.1 / v4.5.0.0 just released, and if all mod_assignment references appear to be removed for the applicable versions we can close this one out.

2025-02-05 17:53 UTC, Syxton commented
Existing changes look good.  Closing! Thanks!

2025-02-05 17:53 UTC, closed without merging